FROM python:3.10-slim

WORKDIR /app

COPY ./requirements.txt /app/requirements.txt
COPY ./src/main/api.py /app/api.py
COPY ./src/test/test_ap.py /app/test_ap.py
COPY ./icd.csv /app/icd.csv
COPY ./icd.pt /app/icd.pt

RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

CMD ["pytest","-v"]
